# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
zstyle ':omz:update' mode auto        # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# omz plugins autoupdate
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

alias z='nocorrect z'
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="true"

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="20"
ZSH_AUTOSUGGEST_USE_ASYNC=1

ZSH_COLORIZE_TOOL=chroma

ZSH_CUSTOM_AUTOUPDATE_NUM_WORKERS=8

plugins=(
  autoupdate
  colorize
  extract
  eza
  git
  git-extras
  command-not-found
  nvm
  docker
  docker-compose
  systemd
  tailscale
  fzf
  zoxide
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# nvm zsh plugin is Very Slow
zstyle ':omz:plugins:nvm' lazy yes

# eza
zstyle ':omz:plugins:eza' 'header' no
zstyle ':omz:plugins:eza' 'dirs-first' yes
zstyle ':omz:plugins:eza' 'git-status' yes
zstyle ':omz:plugins:eza' 'icons' yes
zstyle ':omz:plugins:eza' 'hyperlink' yes

source $ZSH/oh-my-zsh.sh

# User configuration

# sudo prompt
export SUDO_PROMPT="$(tput bel)$(tput setab 1 setaf 7 bold)[sudo]$(tput sgr0) $(tput setaf 6)password for$(tput sgr0) $(tput setaf 5)%p$(tput sgr0): "

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi
alias n="nvim"

# vicinae
alias dmenu="vicinae dmenu"

# Compilation flags
export ARCHFLAGS="-arch $(uname -m)"

# p10k
# source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# kitty
typeset -g POWERLEVEL9K_TERM_SHELL_INTEGRATION=true
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

# bun
export PATH="$HOME/.bun/bin:$HOME/.cache/.bun/bin:$PATH"

# valdi
export ANDROID_HOME="$HOME/Android/Sdk"
export ANDROID_NDK_HOME="$HOME/Android/Sdk/ndk/25.2.9519653"
export PATH="$PATH:$HOME/Android/Sdk/tools"

# Valdi configuration begin
export PATH="$HOME/.valdi/bin:$PATH"
export ANDROID_NDK_HOME="$ANDROID_HOME/ndk-bundle"
# Valdi configuration end

# go
export PATH="$PATH:$HOME/go/bin"

# rust
export PATH="$PATH:$HOME/.cargo/bin"

# home manager
source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh

