-- Auto-generated by Matugen. Do not edit.

return {
	image = "{{image}}",
<* for name, value in colors *>
	{{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
	active_border = "rgba({{colors.primary.default.hex_stripped}}cc)",
	inactive_border = "rgba({{colors.primary.default.hex_stripped}}44)",
}
