-- Auto-generated by Matugen

return {
	{
		"nvim-mini/mini.base16",
		version = false,
		config = function()
			require("mini.base16").setup({
				palette = {
					base00 = "{{colors.background.default.hex}}",
					base01 = "{{colors.surface_container_lowest.default.hex}}",
					base02 = "{{colors.surface_container_low.default.hex}}",
					base03 = "{{colors.outline_variant.default.hex}}",
					base04 = "{{colors.on_surface_variant.default.hex}}",
					base05 = "{{colors.on_surface.default.hex}}",
					base06 = "{{colors.inverse_on_surface.default.hex}}",
					base07 = "{{colors.surface_bright.default.hex}}",

					base08 = "{{colors.error.default.hex | set_lightness: 70.0}}",
					base09 = "{{colors.tertiary.default.hex | set_lightness: 70.0}}",
					base0A = "{{colors.secondary.default.hex | set_lightness: 70.0}}",
					base0B = "{{colors.primary.default.hex | set_lightness: 70.0}}",
					base0C = "{{colors.tertiary_container.default.hex | set_lightness: 70.0}}",
					base0D = "{{colors.primary_container.default.hex | set_lightness: 70.0}}",
					base0E = "{{colors.secondary_container.default.hex | set_lightness: 70.0}}",
					base0F = "{{colors.error_container.default.hex | set_lightness: 70.0}}",
				},

				use_cterm = true,
			})

			vim.api.nvim_set_hl(0, "NeoTreeTabInactive", {
				bg = "{{colors.background.default.hex}}",
				fg = "{{colors.on_surface.default.hex | set_lightness: 70.0}}",
			})

			vim.api.nvim_set_hl(0, "NeoTreeTabActive", {
				bg = "{{colors.surface_container_lowest.default.hex}}",
				fg = "{{colors.primary.default.hex | set_lightness: 70.0}}",
			})
		end,
	},
}
