# MATUGEN GENERATED COLORS

$image = /home/rain/.dotfiles/wallpapers/full-moon-clouds-pink-sky-scenic-aesthetic-2880x1800-1653-darken.png

$background = rgba(181215ff)

$blue = rgba(cebdfeff)

$blue_container = rgba(4c3e76ff)

$blue_source = rgba(0000ffff)

$blue_value = rgba(0000ffff)

$cyan = rgba(82d3e2ff)

$cyan_container = rgba(004e59ff)

$cyan_source = rgba(00ffffff)

$cyan_value = rgba(00ffffff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$green = rgba(b7d085ff)

$green_container = rgba(3a4d10ff)

$green_source = rgba(00ff00ff)

$green_value = rgba(00ff00ff)

$inverse_on_surface = rgba(362e32ff)

$inverse_primary = rgba(844c73ff)

$inverse_surface = rgba(eddfe4ff)

$magenta = rgba(f4b2e2ff)

$magenta_container = rgba(67355dff)

$magenta_source = rgba(ff00ffff)

$magenta_value = rgba(ff00ffff)

$on_background = rgba(eddfe4ff)

$on_blue = rgba(35275eff)

$on_blue_container = rgba(e8ddffff)

$on_cyan = rgba(00363eff)

$on_cyan_container = rgba(9eefffff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_green = rgba(253600ff)

$on_green_container = rgba(d3ec9eff)

$on_magenta = rgba(4e1e46ff)

$on_magenta_container = rgba(ffd7f1ff)

$on_orange = rgba(55200bff)

$on_orange_container = rgba(ffdbcfff)

$on_primary = rgba(4f1e43ff)

$on_primary_container = rgba(ffd7eeff)

$on_primary_fixed = rgba(36072dff)

$on_primary_fixed_variant = rgba(69345aff)

$on_red = rgba(561d26ff)

$on_red_container = rgba(ffdadcff)

$on_secondary = rgba(3f2a37ff)

$on_secondary_container = rgba(fadaecff)

$on_secondary_fixed = rgba(281622ff)

$on_secondary_fixed_variant = rgba(57404eff)

$on_surface = rgba(eddfe4ff)

$on_surface_variant = rgba(d2c2caff)

$on_tertiary = rgba(4b2716ff)

$on_tertiary_container = rgba(ffdbcdff)

$on_tertiary_fixed = rgba(321204ff)

$on_tertiary_fixed_variant = rgba(663c2aff)

$on_yellow = rgba(3b2f00ff)

$on_yellow_container = rgba(fce186ff)

$orange = rgba(ffb59cff)

$orange_container = rgba(72351fff)

$orange_source = rgba(ff8000ff)

$orange_value = rgba(ff8000ff)

$outline = rgba(9b8d94ff)

$outline_variant = rgba(4f444aff)

$primary = rgba(f7b2dfff)

$primary_container = rgba(69345aff)

$primary_fixed = rgba(ffd7eeff)

$primary_fixed_dim = rgba(f7b2dfff)

$red = rgba(ffb2b9ff)

$red_container = rgba(72333bff)

$red_source = rgba(ff0000ff)

$red_value = rgba(ff0000ff)

$scrim = rgba(000000ff)

$secondary = rgba(ddbecfff)

$secondary_container = rgba(57404eff)

$secondary_fixed = rgba(fadaecff)

$secondary_fixed_dim = rgba(ddbecfff)

$shadow = rgba(000000ff)

$source_color = rgba(7c3f6bff)

$surface = rgba(181215ff)

$surface_bright = rgba(3f373bff)

$surface_container = rgba(251e22ff)

$surface_container_high = rgba(2f282cff)

$surface_container_highest = rgba(3a3337ff)

$surface_container_low = rgba(201a1eff)

$surface_container_lowest = rgba(120c10ff)

$surface_dim = rgba(181215ff)

$surface_tint = rgba(f7b2dfff)

$surface_variant = rgba(4f444aff)

$tertiary = rgba(f5b9a1ff)

$tertiary_container = rgba(663c2aff)

$tertiary_fixed = rgba(ffdbcdff)

$tertiary_fixed_dim = rgba(f5b9a1ff)

$yellow = rgba(dec56eff)

$yellow_container = rgba(554500ff)

$yellow_source = rgba(ffff00ff)

$yellow_value = rgba(ffff00ff)


general {
    col.inactive_border = rgba(f7b2df44)
    col.active_border = rgba(f7b2dfcc)
}
