# MATUGEN GENERATED COLORS

$image = /home/rain/.dotfiles/wallpapers/d308f42fb9554fb536f4ec55e1ea1358.jpg

$background = rgba(161217ff)

$blue = rgba(cebdfeff)

$blue_container = rgba(4c3e76ff)

$blue_source = rgba(0000ffff)

$blue_value = rgba(0000ffff)

$cyan = rgba(82d3e2ff)

$cyan_container = rgba(004e59ff)

$cyan_source = rgba(00ffffff)

$cyan_value = rgba(00ffffff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$green = rgba(b7d085ff)

$green_container = rgba(3a4d10ff)

$green_source = rgba(00ff00ff)

$green_value = rgba(00ff00ff)

$inverse_on_surface = rgba(342f34ff)

$inverse_primary = rgba(774f83ff)

$inverse_surface = rgba(eae0e7ff)

$magenta = rgba(ecb4ecff)

$magenta_container = rgba(623765ff)

$magenta_source = rgba(ff00ffff)

$magenta_value = rgba(ff00ffff)

$on_background = rgba(eae0e7ff)

$on_blue = rgba(35275eff)

$on_blue_container = rgba(e8ddffff)

$on_cyan = rgba(00363eff)

$on_cyan_container = rgba(9eefffff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_green = rgba(253600ff)

$on_green_container = rgba(d3ec9eff)

$on_magenta = rgba(49204dff)

$on_magenta_container = rgba(ffd6fdff)

$on_orange = rgba(55200bff)

$on_orange_container = rgba(ffdbcfff)

$on_primary = rgba(462152ff)

$on_primary_container = rgba(fad7ffff)

$on_primary_fixed = rgba(2e0a3bff)

$on_primary_fixed_variant = rgba(5e386aff)

$on_red = rgba(561d26ff)

$on_red_container = rgba(ffdadcff)

$on_secondary = rgba(3a2b3dff)

$on_secondary_container = rgba(f2dcf3ff)

$on_secondary_fixed = rgba(241727ff)

$on_secondary_fixed_variant = rgba(514254ff)

$on_surface = rgba(eae0e7ff)

$on_surface_variant = rgba(cfc3cdff)

$on_tertiary = rgba(4c2523ff)

$on_tertiary_container = rgba(ffdad7ff)

$on_tertiary_fixed = rgba(33110fff)

$on_tertiary_fixed_variant = rgba(663b38ff)

$on_yellow = rgba(3b2f00ff)

$on_yellow_container = rgba(fce186ff)

$orange = rgba(ffb59cff)

$orange_container = rgba(72351fff)

$orange_source = rgba(ff8000ff)

$orange_value = rgba(ff8000ff)

$outline = rgba(988e97ff)

$outline_variant = rgba(4c444cff)

$primary = rgba(e6b6f1ff)

$primary_container = rgba(5e386aff)

$primary_fixed = rgba(fad7ffff)

$primary_fixed_dim = rgba(e6b6f1ff)

$red = rgba(ffb2b9ff)

$red_container = rgba(72333bff)

$red_source = rgba(ff0000ff)

$red_value = rgba(ff0000ff)

$scrim = rgba(000000ff)

$secondary = rgba(d5c0d7ff)

$secondary_container = rgba(514254ff)

$secondary_fixed = rgba(f2dcf3ff)

$secondary_fixed_dim = rgba(d5c0d7ff)

$shadow = rgba(000000ff)

$source_color = rgba(63486aff)

$surface = rgba(161217ff)

$surface_bright = rgba(3d373dff)

$surface_container = rgba(231e23ff)

$surface_container_high = rgba(2d282eff)

$surface_container_highest = rgba(393339ff)

$surface_container_low = rgba(1f1a1fff)

$surface_container_lowest = rgba(110d12ff)

$surface_dim = rgba(161217ff)

$surface_tint = rgba(e6b6f1ff)

$surface_variant = rgba(4c444cff)

$tertiary = rgba(f5b7b3ff)

$tertiary_container = rgba(663b38ff)

$tertiary_fixed = rgba(ffdad7ff)

$tertiary_fixed_dim = rgba(f5b7b3ff)

$yellow = rgba(dec56eff)

$yellow_container = rgba(554500ff)

$yellow_source = rgba(ffff00ff)

$yellow_value = rgba(ffff00ff)


general {
    col.inactive_border = rgba(e6b6f144)
    col.active_border = rgba(e6b6f1cc)
}
