# MATUGEN GENERATED COLORS

$image = /home/rain/Downloads/126660551_p0_cut.jpg

$background = rgba(0f1417ff)

$blue = rgba(afc6ffff)

$blue_container = rgba(2d4578ff)

$blue_source = rgba(0000ffff)

$blue_value = rgba(0000ffff)

$cyan = rgba(82d3e2ff)

$cyan_container = rgba(004f59ff)

$cyan_source = rgba(00ffffff)

$cyan_value = rgba(00ffffff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$green = rgba(95d5a7ff)

$green_container = rgba(10512fff)

$green_source = rgba(00ff00ff)

$green_value = rgba(00ff00ff)

$inverse_on_surface = rgba(2c3134ff)

$inverse_primary = rgba(0b6780ff)

$inverse_surface = rgba(dee3e6ff)

$magenta = rgba(e4b7f3ff)

$magenta_container = rgba(5c386bff)

$magenta_source = rgba(ff00ffff)

$magenta_value = rgba(ff00ffff)

$on_background = rgba(dee3e6ff)

$on_blue = rgba(142f60ff)

$on_blue_container = rgba(d9e2ffff)

$on_cyan = rgba(00363eff)

$on_cyan_container = rgba(9eefffff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_green = rgba(00391dff)

$on_green_container = rgba(b0f1c2ff)

$on_magenta = rgba(442253ff)

$on_magenta_container = rgba(f7d8ffff)

$on_orange = rgba(482900ff)

$on_orange_container = rgba(ffddbbff)

$on_primary = rgba(003544ff)

$on_primary_container = rgba(b9eaffff)

$on_primary_fixed = rgba(001f29ff)

$on_primary_fixed_variant = rgba(004d62ff)

$on_red = rgba(561d26ff)

$on_red_container = rgba(ffdadcff)

$on_secondary = rgba(1e333cff)

$on_secondary_container = rgba(cfe6f1ff)

$on_secondary_fixed = rgba(071e26ff)

$on_secondary_fixed_variant = rgba(354a53ff)

$on_surface = rgba(dee3e6ff)

$on_surface_variant = rgba(c0c8ccff)

$on_tertiary = rgba(2d2d4dff)

$on_tertiary_container = rgba(e1dfffff)

$on_tertiary_fixed = rgba(181837ff)

$on_tertiary_fixed_variant = rgba(434465ff)

$on_yellow = rgba(263500ff)

$on_yellow_container = rgba(d4ec9dff)

$orange = rgba(faba73ff)

$orange_container = rgba(673d00ff)

$orange_source = rgba(ff8000ff)

$orange_value = rgba(ff8000ff)

$outline = rgba(8a9296ff)

$outline_variant = rgba(40484cff)

$primary = rgba(89d0edff)

$primary_container = rgba(004d62ff)

$primary_fixed = rgba(b9eaffff)

$primary_fixed_dim = rgba(89d0edff)

$red = rgba(ffb2b9ff)

$red_container = rgba(72333bff)

$red_source = rgba(ff0000ff)

$red_value = rgba(ff0000ff)

$scrim = rgba(000000ff)

$secondary = rgba(b3cad5ff)

$secondary_container = rgba(354a53ff)

$secondary_fixed = rgba(cfe6f1ff)

$secondary_fixed_dim = rgba(b3cad5ff)

$shadow = rgba(000000ff)

$source_color = rgba(1b323bff)

$surface = rgba(0f1417ff)

$surface_bright = rgba(353a3dff)

$surface_container = rgba(1b2023ff)

$surface_container_high = rgba(252b2dff)

$surface_container_highest = rgba(303638ff)

$surface_container_low = rgba(171c1fff)

$surface_container_lowest = rgba(0a0f11ff)

$surface_dim = rgba(0f1417ff)

$surface_tint = rgba(89d0edff)

$surface_variant = rgba(40484cff)

$tertiary = rgba(c4c3ebff)

$tertiary_container = rgba(434465ff)

$tertiary_fixed = rgba(e1dfffff)

$tertiary_fixed_dim = rgba(c4c3ebff)

$yellow = rgba(b8cf84ff)

$yellow_container = rgba(3b4d0fff)

$yellow_source = rgba(ffff00ff)

$yellow_value = rgba(ffff00ff)


general {
    col.inactive_border = rgba(89d0ed44)
    col.active_border = rgba(89d0edcc)
}
