#!/bin/sh

clamp() {
  min=$1
  max=$2
  val=$3

  if [ "$val" -lt "$min" ]; then
    echo "$min"
  elif [ "$val" -gt "$max" ]; then
    echo "$max"
  else
    echo "$val"
  fi
}

direction=$1
current=$2
if [ "$direction" = "down" ]; then
  target=$(clamp 1 10 $((current + 1)))
  echo "jumping to $target"
  hyprctl dispatch workspace $target
elif [ "$direction" = "up" ]; then
  target=$(clamp 1 10 $((current - 1)))
  echo "jumping to $target"
  hyprctl dispatch workspace $target
fi
