#!/bin/sh

spaces() {
  # not particularly efficient, but it works fine
  # about 9ms to process
  workspaces=$(hyprctl workspaces -j)
  clients=$(hyprctl clients -j)
  monitors=$(hyprctl monitors -j)

  # return a json array of workspaces with the following fields:
  # id: the workspace id
  # name: the workspace name
  # windows: the number of windows in the workspace
  # tags: an array of tags that clients on the workspace have
  # monitor: the name of the monitor the workspace is on, or null
  # focused: true if the monitor is focused and has this workspace, otherwise false/null

  jq -Mcn --argjson workspaces "$workspaces" --argjson clients "$clients" --argjson monitors "$monitors" '
    $workspaces
    | map(select(.id > 0))
    | map(
        . as $ws
        | (
            $clients
            | map(select(.workspace.id == $ws.id and .tags != null and (.tags | length > 0)))
            | map(.tags | .[]) 
          ) as $tags
        | ($monitors | map(select(.activeWorkspace.id == $ws.id)) | .[0]) as $monitor
        | {
            id: $ws.id,
            name: $ws.name,
            windows: $ws.windows,
            tags: $tags,
            tagsList: ($tags | unique | join(" ")),
            monitor: ($monitor.name // ""),
            focused: ($monitor.focused // false)
          }
      )
    | sort_by(.id)
  '
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r _; do
  spaces
done
