#!/bin/sh

spaces() {
  workspaces=$(hyprctl workspaces -j)
  clients=$(hyprctl clients -j)

  # return a json array of workspaces with the following fields:
  # id: the workspace id
  # name: the workspace name
  # windows: the number of windows in the workspace
  # tags: an array of tags that clients on the workspace have
  result=$(
    jq -Mcn --argjson workspaces "$workspaces" --argjson clients "$clients" '
      $workspaces
      | map(select(.id > 0))
      | map(
          . as $ws
          | (
              $clients
              | map(select(.workspace.id == $ws.id and .tags != null and .tags != []))
              | map(.tags[])
            ) as $tags
          | {
              id: $ws.id,
              name: $ws.name,
              windows: $ws.windows,
              tags: $tags,
              tagsList: ($tags | unique | join(" ") // "")
            }
        )
      | sort_by(.id)
    '
  )
  echo $result
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  spaces
done
