#!/bin/sh

spaces() {
  hyprctl workspaces -j | jq -Mc 'map({id: .id, name: .name, windows: .windows}) | map(select(.id > 0)) | sort_by(.id)'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  spaces
done
