# window tagger from xdg bell and pings
exec-once = uwsm-app -a "hyprland_autotag_bg" -s b -- bash ~/.config/hypr/scripts/bg/autotag.sh

# tags
windowrule {
  name = errored-window
  border_color = $error $error
  match:tag = bell
}

windowrule {
  name = urgent-window
  border_color = $error_container $error_container
  match:tag = urgent
}
