# should maybe provide custom service unit for background target
exec-once = uwsm-app -- eww open bar &2> /dev/null

layerrule {
  name = bars
  blur = on
  ignore_alpha = 0
  match:namespace = ^(waybar|eww)$
}
