-- Auto-generated by Matugen

return {
	{
		"nvim-mini/mini.base16",
		version = false,
		config = function()
			require("mini.base16").setup({
				palette = {
					base00 = "#171216",
					base01 = "#120d11",
					base02 = "#1f1a1f",
					base03 = "#4d444c",
					base04 = "#d0c3cc",
					base05 = "#ebdfe6",
					base06 = "#352f34",
					base07 = "#3e373c",

					base08 = "#ff7666",
					base09 = "#f08975",
					base0A = "#c5a0bf",
					base0B = "#e184de",
					base0C = "#cca199",
					base0D = "#c79bca",
					base0E = "#bca9bb",
					base0F = "#ff6670",
				},

				use_cterm = true,
			})

			vim.api.nvim_set_hl(0, "NeoTreeTabInactive", {
				bg = "#171216",
				fg = "#c4a1b5",
			})

			vim.api.nvim_set_hl(0, "NeoTreeTabActive", {
				bg = "#120d11",
				fg = "#e184de",
			})
		end,
	},
}
