-- Auto-generated by Matugen

return {
	{
		"nvim-mini/mini.base16",
		version = false,
		config = function()
			require("mini.base16").setup({
				palette = {
					base00 = "#161217",
					base01 = "#110d12",
					base02 = "#1f1a1f",
					base03 = "#4c444c",
					base04 = "#cfc3cd",
					base05 = "#eae0e7",
					base06 = "#342f34",
					base07 = "#3d373d",

					base08 = "#ff7666",
					base09 = "#ed7f78",
					base0A = "#c1a1c4",
					base0B = "#d37fe6",
					base0C = "#c99f9c",
					base0D = "#bf9bca",
					base0E = "#b9a9bc",
					base0F = "#ff6670",
				},

				use_cterm = true,
			})

			vim.api.nvim_set_hl(0, "NeoTreeTabInactive", {
				bg = "#161217",
				fg = "#c1a4b8",
			})

			vim.api.nvim_set_hl(0, "NeoTreeTabActive", {
				bg = "#110d12",
				fg = "#d37fe6",
			})
		end,
	},
}
