-- Auto-generated by Matugen. Do not edit.

return {
	image = "/home/rain/.dotfiles/wallpapers/full-moon-clouds-pink-sky-scenic-aesthetic-2880x1800-1653-darken.png",

	background = "rgba(151218ff)",

	blue = "rgba(cdbdffff)",

	blue_container = "rgba(4a3e76ff)",

	blue_source = "rgba(0000ffff)",

	blue_value = "rgba(0000ffff)",

	cyan = "rgba(82d3e2ff)",

	cyan_container = "rgba(004e59ff)",

	cyan_source = "rgba(00ffffff)",

	cyan_value = "rgba(00ffffff)",

	error = "rgba(ffb4abff)",

	error_container = "rgba(93000aff)",

	green = "rgba(95d5a7ff)",

	green_container = "rgba(10512fff)",

	green_source = "rgba(00ff00ff)",

	green_value = "rgba(00ff00ff)",

	inverse_on_surface = "rgba(332f35ff)",

	inverse_primary = "rgba(6e528aff)",

	inverse_surface = "rgba(e8e0e8ff)",

	magenta = "rgba(e7b6f1ff)",

	magenta_container = "rgba(5e386aff)",

	magenta_source = "rgba(ff00ffff)",

	magenta_value = "rgba(ff00ffff)",

	on_background = "rgba(e8e0e8ff)",

	on_blue = "rgba(34275eff)",

	on_blue_container = "rgba(e7deffff)",

	on_cyan = "rgba(00363eff)",

	on_cyan_container = "rgba(9eefffff)",

	on_error = "rgba(690005ff)",

	on_error_container = "rgba(ffdad6ff)",

	on_green = "rgba(00391dff)",

	on_green_container = "rgba(b0f1c2ff)",

	on_magenta = "rgba(462151ff)",

	on_magenta_container = "rgba(fad7ffff)",

	on_orange = "rgba(55200bff)",

	on_orange_container = "rgba(ffdbcfff)",

	on_primary = "rgba(3e2459ff)",

	on_primary_container = "rgba(f0dbffff)",

	on_primary_fixed = "rgba(280d42ff)",

	on_primary_fixed_variant = "rgba(563b71ff)",

	on_red = "rgba(561d26ff)",

	on_red_container = "rgba(ffdadcff)",

	on_secondary = "rgba(362c3fff)",

	on_secondary_container = "rgba(edddf6ff)",

	on_secondary_fixed = "rgba(211829ff)",

	on_secondary_fixed_variant = "rgba(4d4356ff)",

	on_surface = "rgba(e8e0e8ff)",

	on_surface_variant = "rgba(ccc4ceff)",

	on_tertiary = "rgba(4b252bff)",

	on_tertiary_container = "rgba(ffd9ddff)",

	on_tertiary_fixed = "rgba(321017ff)",

	on_tertiary_fixed_variant = "rgba(653a41ff)",

	on_yellow = "rgba(3b2f00ff)",

	on_yellow_container = "rgba(fce186ff)",

	orange = "rgba(ffb59cff)",

	orange_container = "rgba(72351fff)",

	orange_source = "rgba(ff8000ff)",

	orange_value = "rgba(ff8000ff)",

	outline = "rgba(968e98ff)",

	outline_variant = "rgba(4a454eff)",

	primary = "rgba(dbb9f9ff)",

	primary_container = "rgba(563b71ff)",

	primary_fixed = "rgba(f0dbffff)",

	primary_fixed_dim = "rgba(dbb9f9ff)",

	red = "rgba(ffb2b9ff)",

	red_container = "rgba(72333bff)",

	red_source = "rgba(ff0000ff)",

	red_value = "rgba(ff0000ff)",

	scrim = "rgba(000000ff)",

	secondary = "rgba(d0c1daff)",

	secondary_container = "rgba(4d4356ff)",

	secondary_fixed = "rgba(edddf6ff)",

	secondary_fixed_dim = "rgba(d0c1daff)",

	shadow = "rgba(000000ff)",

	source_color = "rgba(3d2a50ff)",

	surface = "rgba(151218ff)",

	surface_bright = "rgba(3c383eff)",

	surface_container = "rgba(221e24ff)",

	surface_container_high = "rgba(2c292eff)",

	surface_container_highest = "rgba(373339ff)",

	surface_container_low = "rgba(1e1a20ff)",

	surface_container_lowest = "rgba(100d12ff)",

	surface_dim = "rgba(151218ff)",

	surface_tint = "rgba(dbb9f9ff)",

	surface_variant = "rgba(4a454eff)",

	tertiary = "rgba(f3b7beff)",

	tertiary_container = "rgba(653a41ff)",

	tertiary_fixed = "rgba(ffd9ddff)",

	tertiary_fixed_dim = "rgba(f3b7beff)",

	yellow = "rgba(dec56eff)",

	yellow_container = "rgba(554500ff)",

	yellow_source = "rgba(ffff00ff)",

	yellow_value = "rgba(ffff00ff)",

	active_border = "rgba(dbb9f9cc)",
	inactive_border = "rgba(dbb9f944)",
}
