cursor #eae0e7
cursor_text_color #cfc3cd

foreground            #eae0e7
background            #150e17
selection_foreground  #3a2b3d
selection_background  #d5c0d7
url_color             #e6b6f1

color0 #312834
color1 #ff8678
color2 #c0a1c3
color3 #b7a8ba
color4 #d78be9
color5 #ef8c86
color6 #cba29f
color7 #d5c2cf

color8  #cfc3cd
color9  #ffe2de
color10 #eadfeb
color11 #886f8d
color12 #f5e1f9
color13 #fbe2e0
color14 #a6625e
color15 #fffeff
