cursor #dee3e6
cursor_text_color #c0c8cc

foreground            #dee3e6
background            #030d10
selection_foreground  #1e333c
selection_background  #b3cad5
url_color             #89d0ed

color0 #232f36
color1 #ff8678
color2 #92b3c3
color3 #97b2bd
color4 #5dbee6
color5 #9e9dde
color6 #acadc8
color7 #c1cad0

color8  #c0c8cc
color9  #ffe2de
color10 #d4e1e7
color11 #5d8291
color12 #b5e2f4
color13 #eae9f8
color14 #6f709f
color15 #fbfcfc
